version: '3.1'
services:
  humhub:
    build: .
    environment:
      HUMHUB_DB_USER: ${HUMHUB_DB_USER}
      HUMHUB_DB_PASSWORD: ${HUMHUB_DB_PASSWORD}
      HUMHUB_ADMIN_USER: ${HUMHUB_ADMIN_USER}
      HUMHUB_ADMIN_EMAIL: ${HUMHUB_ADMIN_EMAIL}
      HUMHUB_ADMIN_PASSWORD: ${HUMHUB_ADMIN_PASSWORD}
      HUMHUB_DB_HOST: 'db'
      HUMHUB_DB_NAME: 'humhub'
      HUMHUB_AUTO_INSTALL: 'true'
      HUMHUB_DEBUG: 'true'
      HUMHUB_PROTO: 'https'
      HUMHUB_HOST: 'localhost'
      HUMHUB_SUB_DIR: '/humhub'
      PHP_MAX_EXECUTION_TIME: 321
      PHP_UPLOAD_MAX_FILESIZE: 6M
      PHP_POST_MAX_SIZE: 7M
    ports:
    - "80:80"
#   volumes:
#     - "${HUMHUB_VOLUME_CONFIG}:/var/www/localhost/htdocs/protected/config"
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost/"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: 'humhub'
      MYSQL_USER: ${HUMHUB_DB_USER}
      MYSQL_PASSWORD: ${HUMHUB_DB_PASSWORD}
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "--silent"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
