version: '3.1'
services:
  humhub:
    build: .
    environment:
      HUMHUB_DB_USER: ${HUMHUB_DB_USER}
      HUMHUB_DB_PASSWORD: ${HUMHUB_DB_PASSWORD}
      HUMHUB_AUTO_INSTALL: 'true'
      HUMHUB_DEBUG: 'true'
      HUMHUB_HOST: 'http://localhost'
      HUMHUB_BASE_URL: 'http://localhost/humhub'
      PHP_MAX_EXECUTION_TIME: 321
      PHP_UPLOAD_MAX_FILESIZE: 6M
      PHP_POST_MAX_SIZE: 7M

#   volumes:
#     - "${HUMHUB_VOLUME_CONFIG}:/var/www/localhost/htdocs/protected/config"
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost/humhub"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: 'humhub'
      MYSQL_USER: ${HUMHUB_DB_USER}
      MYSQL_PASSWORD: ${HUMHUB_DB_PASSWORD}
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "--silent"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
  proxy:
    image: nginx:stable
    volumes:
      - ./proxy/app.conf:/etc/nginx/conf.d/app.conf
    ports:
      - "80:80"
